### ISSUE TITLE
前端｜美联储披露持仓，图表出展示现问题, 超过能力范围

### ISSUE THREAD

**Issue by beadth** [beadth/beadth.github.io#5]
- [ ] 数据图表出展示现问题，水平有限暂时解决不了

问题复现：site 分支 项目中搜索TODO查看指引

![image](https://user-images.githubusercontent.com/73101124/100416919-9c581280-30ba-11eb-8431-0db12442c7bb.png)

**Comment by ocean0212** [comment]
I am working on this, will have a pull request soon.

**Comment by beadth** [comment]
碰到同样的情况，本应该是数值，而它出现了字符串
